/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.repository;

import com.example.demo.entity.Books;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for Books.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface BooksRepository  extends JpaRepository<Books, Integer> {
	Books findByIsbn(Integer isbn);
	
}