package com.example.demo.entity;
// Generated Sep 28, 2018 9:48:26 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.transaction.annotation.Transactional;

/**
 * Books generated by hbm2java
 */
@Entity
@Table(name = "books", catalog = "librares")

public class Books implements java.io.Serializable {

	private Long isbn;
	private String bookTitle;
	private Date dateOfPublication;
	private Set booksAtLibrarieses = new HashSet(0);
	private Set booksByAuthors = new HashSet(0);
	private Set booksByCategories = new HashSet(0);

	public Books() {
	}

	public Books(String bookTitle, Date dateOfPublication, Set booksAtLibrarieses, Set booksByAuthors,
			Set booksByCategories) {
		this.bookTitle = bookTitle;
		this.dateOfPublication = dateOfPublication;
		this.booksAtLibrarieses = booksAtLibrarieses;
		this.booksByAuthors = booksByAuthors;
		this.booksByCategories = booksByCategories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "isbn", unique = true, nullable = false)
	public Long getIsbn() {
		return this.isbn;
	}

	public void setIsbn(Long isbn) {
		this.isbn = isbn;
	}

	@Column(name = "book_title", length = 45)
	public String getBookTitle() {
		return this.bookTitle;
	}

	public void setBookTitle(String bookTitle) {
		this.bookTitle = bookTitle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_publication", length = 19)
	public Date getDateOfPublication() {
		return this.dateOfPublication;
	}

	public void setDateOfPublication(Date dateOfPublication) {
		this.dateOfPublication = dateOfPublication;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "books")
	public Set getBooksAtLibrarieses() {
		return this.booksAtLibrarieses;
	}

	public void setBooksAtLibrarieses(Set booksAtLibrarieses) {
		this.booksAtLibrarieses = booksAtLibrarieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "books")
	public Set getBooksByAuthors() {
		return this.booksByAuthors;
	}

	public void setBooksByAuthors(Set booksByAuthors) {
		this.booksByAuthors = booksByAuthors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "books")
	public Set getBooksByCategories() {
		return this.booksByCategories;
	}

	public void setBooksByCategories(Set booksByCategories) {
		this.booksByCategories = booksByCategories;
	}

}
