package com.example.demo.entity;
// Generated Sep 28, 2018 2:22:56 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Books generated by hbm2java
 */
@Entity
@Table(name = "books", catalog = "librares")
public class Books implements java.io.Serializable {

	private Long isbn;
	private String bookTitle;
	private Date dateOfPublication;
	private Set<BooksAtLibraries> booksAtLibrarieses = new HashSet<BooksAtLibraries>(0);
	private Set<BooksByAuthor> booksByAuthors = new HashSet<BooksByAuthor>(0);
	private Set<BooksByCategory> booksByCategories = new HashSet<BooksByCategory>(0);

	public Books() {
	}

	public Books(String bookTitle, Date dateOfPublication, Set<BooksAtLibraries> booksAtLibrarieses,
			Set<BooksByAuthor> booksByAuthors, Set<BooksByCategory> booksByCategories) {
		this.bookTitle = bookTitle;
		this.dateOfPublication = dateOfPublication;
		this.booksAtLibrarieses = booksAtLibrarieses;
		this.booksByAuthors = booksByAuthors;
		this.booksByCategories = booksByCategories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "isbn", unique = true, nullable = false)
	public Long getIsbn() {
		return this.isbn;
	}

	public void setIsbn(Long isbn) {
		this.isbn = isbn;
	}

	@Column(name = "book_title", length = 45)
	public String getBookTitle() {
		return this.bookTitle;
	}

	public void setBookTitle(String bookTitle) {
		this.bookTitle = bookTitle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_publication", length = 19)
	public Date getDateOfPublication() {
		return this.dateOfPublication;
	}

	public void setDateOfPublication(Date dateOfPublication) {
		this.dateOfPublication = dateOfPublication;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "books")
	public Set<BooksAtLibraries> getBooksAtLibrarieses() {
		return this.booksAtLibrarieses;
	}

	public void setBooksAtLibrarieses(Set<BooksAtLibraries> booksAtLibrarieses) {
		this.booksAtLibrarieses = booksAtLibrarieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "books")
	public Set<BooksByAuthor> getBooksByAuthors() {
		return this.booksByAuthors;
	}

	public void setBooksByAuthors(Set<BooksByAuthor> booksByAuthors) {
		this.booksByAuthors = booksByAuthors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "books")
	public Set<BooksByCategory> getBooksByCategories() {
		return this.booksByCategories;
	}

	public void setBooksByCategories(Set<BooksByCategory> booksByCategories) {
		this.booksByCategories = booksByCategories;
	}

}
