package com.example.demo.entity;
// Generated Sep 28, 2018 9:48:26 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BooksByAuthor generated by hbm2java
 */
@Entity
@Table(name = "books_by_author", catalog = "librares")
public class BooksByAuthor implements java.io.Serializable {

	private Long booksHasAuthorsid;
	private Authors authors;
	private Books books;

	public BooksByAuthor() {
	}

	public BooksByAuthor(Authors authors, Books books) {
		this.authors = authors;
		this.books = books;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "books_has_authorsid", unique = true, nullable = false)
	public Long getBooksHasAuthorsid() {
		return this.booksHasAuthorsid;
	}

	public void setBooksHasAuthorsid(Long booksHasAuthorsid) {
		this.booksHasAuthorsid = booksHasAuthorsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "authors_author_id", nullable = false)
	public Authors getAuthors() {
		return this.authors;
	}

	public void setAuthors(Authors authors) {
		this.authors = authors;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "isbn", nullable = false)
	public Books getBooks() {
		return this.books;
	}

	public void setBooks(Books books) {
		this.books = books;
	}

}
