package com.example.demo.entity;
// Generated Sep 28, 2018 2:22:56 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Libraries generated by hbm2java
 */
@Entity
@Table(name = "libraries", catalog = "librares")
public class Libraries implements java.io.Serializable {

	private Long libraryId;
	private Addresses addresses;
	private String libraryName;
	private String libraryDetails;
	private Set<BooksAtLibraries> booksAtLibrarieses = new HashSet<BooksAtLibraries>(0);

	public Libraries() {
	}

	public Libraries(Long libraryId, Addresses addresses) {
		this.libraryId = libraryId;
		this.addresses = addresses;
	}

	public Libraries(Long libraryId, Addresses addresses, String libraryName, String libraryDetails,
			Set<BooksAtLibraries> booksAtLibrarieses) {
		this.libraryId = libraryId;
		this.addresses = addresses;
		this.libraryName = libraryName;
		this.libraryDetails = libraryDetails;
		this.booksAtLibrarieses = booksAtLibrarieses;
	}

	@Id

	@Column(name = "library_id", unique = true, nullable = false)
	public Long getLibraryId() {
		return this.libraryId;
	}

	public void setLibraryId(Long libraryId) {
		this.libraryId = libraryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id", nullable = false)
	public Addresses getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Addresses addresses) {
		this.addresses = addresses;
	}

	@Column(name = "library_name", length = 45)
	public String getLibraryName() {
		return this.libraryName;
	}

	public void setLibraryName(String libraryName) {
		this.libraryName = libraryName;
	}

	@Column(name = "library_details", length = 45)
	public String getLibraryDetails() {
		return this.libraryDetails;
	}

	public void setLibraryDetails(String libraryDetails) {
		this.libraryDetails = libraryDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "libraries")
	public Set<BooksAtLibraries> getBooksAtLibrarieses() {
		return this.booksAtLibrarieses;
	}

	public void setBooksAtLibrarieses(Set<BooksAtLibraries> booksAtLibrarieses) {
		this.booksAtLibrarieses = booksAtLibrarieses;
	}

}
