package com.example.demo.entity;
// Generated Sep 28, 2018 9:48:26 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Members generated by hbm2java
 */
@Entity
@Table(name = "members", catalog = "librares")
public class Members implements java.io.Serializable {

	private Long memberId;
	private Addresses addresses;
	private String gender;
	private String memberFirstName;
	private String memberLastName;
	private String phoneNumber;
	private String emailAddress;
	private String otherMemberDetails;

	public Members() {
	}

	public Members(Addresses addresses) {
		this.addresses = addresses;
	}

	public Members(Addresses addresses, String gender, String memberFirstName, String memberLastName,
			String phoneNumber, String emailAddress, String otherMemberDetails) {
		this.addresses = addresses;
		this.gender = gender;
		this.memberFirstName = memberFirstName;
		this.memberLastName = memberLastName;
		this.phoneNumber = phoneNumber;
		this.emailAddress = emailAddress;
		this.otherMemberDetails = otherMemberDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "member_id", unique = true, nullable = false)
	public Long getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Long memberId) {
		this.memberId = memberId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id", nullable = false)
	public Addresses getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Addresses addresses) {
		this.addresses = addresses;
	}

	@Column(name = "gender", length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "member_first_name", length = 45)
	public String getMemberFirstName() {
		return this.memberFirstName;
	}

	public void setMemberFirstName(String memberFirstName) {
		this.memberFirstName = memberFirstName;
	}

	@Column(name = "member_last_name", length = 45)
	public String getMemberLastName() {
		return this.memberLastName;
	}

	public void setMemberLastName(String memberLastName) {
		this.memberLastName = memberLastName;
	}

	@Column(name = "phone_number", length = 45)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "email_address", length = 45)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "other_member_details", length = 45)
	public String getOtherMemberDetails() {
		return this.otherMemberDetails;
	}

	public void setOtherMemberDetails(String otherMemberDetails) {
		this.otherMemberDetails = otherMemberDetails;
	}

}
