/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 06:31:38 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.controller;

import com.example.demo.entity.Books;
import com.example.demo.service.BooksService;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.MediaType;

@RestController
@CrossOrigin(origins = "*")
@RequestMapping(value = "/books", produces = "application/hal+json")
public class BooksController {

	private static final Logger LOGGER = LoggerFactory.getLogger(BooksController.class);

	private static final String NOT_FOUND ="Books not found";

	@Autowired
	private BooksService booksService;

	@RequestMapping(value = "/",
			produces = { MediaType.APPLICATION_JSON_VALUE })
	public List<Books> findAll() {
		List<Books> list = booksService.findAll();
		return list;
	}


	@GetMapping("{isbn}")
	public Books get(@PathVariable("isbn") Integer isbn) {
		final Books books = booksService.getOne(isbn);
		LOGGER.info("Books found : {}", books);
		return books;
	}

	@PostMapping(value="/create/",consumes = "application/json")
	public Books create(@RequestBody Books books) {
		LOGGER.info("Books creation request : {}", books);
		if (booksService.exist(books)) {
			LOGGER.info("Books already exist ! : {}", books);
			return null;
		} else {
			
			final Books created = booksService.create(books);
			LOGGER.info("Created books {}", created);
			return created;
		}
	}

	@PutMapping(value="/save/",consumes = "application/json")
	public Boolean update(@RequestBody Books books) {
		System.out.println(books.getIsbn());
		return booksService.update(books);
	}

	@DeleteMapping("{isbn}")
	public void delete(@PathVariable("isbn") Integer isbn) {
		LOGGER.info("Books deletion request : {}", resolveIdForLogger(isbn));
		if (booksService.delete(isbn)) {
			LOGGER.info("Books succesfully deleted");
		} else {
			LOGGER.info(NOT_FOUND);
		}
	}

	private String resolveIdForLogger(Integer isbn) {
		final StringBuilder ids = new StringBuilder();
		ids.append(String.valueOf(isbn));
		return ids.toString();
	}

}


