/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 06:31:38 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.controller;

import com.example.demo.entity.Members;
import com.example.demo.service.MembersService;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.MediaType;

@RestController
@CrossOrigin(origins = "*")
@RequestMapping(value = "/members", produces = "application/hal+json")
public class MembersController {

	private static final Logger LOGGER = LoggerFactory.getLogger(MembersController.class);

	private static final String NOT_FOUND ="Members not found";

	@Autowired
	private MembersService membersService;

	@RequestMapping(value = "/",
			produces = { MediaType.APPLICATION_JSON_VALUE })
	public List<Members> findAll() {
		List<Members> list = membersService.findAll();
		return list;
	}


	@GetMapping("{memberId}")
	public Members get(@PathVariable("memberId") Integer memberId) {
		final Members members = membersService.getOne(memberId);
		LOGGER.info("Members found : {}", members);
		return members;
	}

	@PostMapping(value="/create/",consumes = "application/json")
	public Members create(@RequestBody Members members) {
		LOGGER.info("Members creation request : {}", members);
		if (membersService.exist(members)) {
			LOGGER.info("Members already exist ! : {}", members);
			return null;
		} else {
			final Members created = membersService.create(members);
			LOGGER.info("Created members {}", created);
			return created;
		}
	}

	@PutMapping(value="/save/",consumes = "application/json")
	public Boolean update(@RequestBody Members members) {
		return membersService.update(members);
	}

	@DeleteMapping("{memberId}")
	public void delete(@PathVariable("memberId") Integer memberId) {
		LOGGER.info("Members deletion request : {}", resolveIdForLogger(memberId));
		if (membersService.delete(memberId)) {
			LOGGER.info("Members succesfully deleted");
		} else {
			LOGGER.info(NOT_FOUND);
		}
	}

	private String resolveIdForLogger(Integer memberId) {
		final StringBuilder ids = new StringBuilder();
		ids.append(String.valueOf(memberId));
		return ids.toString();
	}

}


