package com.example.demo;
// Generated Sep 28, 2018 9:42:18 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Authors generated by hbm2java
 */
@Entity
@Table(name = "authors", catalog = "librares")
public class Authors implements java.io.Serializable {

	private Integer authorId;
	private String authorFirstName;
	private String authorLastName;
	private Set booksByAuthors = new HashSet(0);

	public Authors() {
	}

	public Authors(String authorFirstName, String authorLastName, Set booksByAuthors) {
		this.authorFirstName = authorFirstName;
		this.authorLastName = authorLastName;
		this.booksByAuthors = booksByAuthors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "author_id", unique = true, nullable = false)
	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	@Column(name = "author_first_name", length = 45)
	public String getAuthorFirstName() {
		return this.authorFirstName;
	}

	public void setAuthorFirstName(String authorFirstName) {
		this.authorFirstName = authorFirstName;
	}

	@Column(name = "author_last_name", length = 45)
	public String getAuthorLastName() {
		return this.authorLastName;
	}

	public void setAuthorLastName(String authorLastName) {
		this.authorLastName = authorLastName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "authors")
	public Set getBooksByAuthors() {
		return this.booksByAuthors;
	}

	public void setBooksByAuthors(Set booksByAuthors) {
		this.booksByAuthors = booksByAuthors;
	}

}
