package com.example.demo;
// Generated Sep 28, 2018 9:42:18 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BooksAtLibraries generated by hbm2java
 */
@Entity
@Table(name = "books_at_libraries", catalog = "librares")
public class BooksAtLibraries implements java.io.Serializable {

	private Integer booksHasLibrariesid;
	private Books books;
	private Libraries libraries;
	private Integer quantityInStock;

	public BooksAtLibraries() {
	}

	public BooksAtLibraries(Books books, Libraries libraries) {
		this.books = books;
		this.libraries = libraries;
	}

	public BooksAtLibraries(Books books, Libraries libraries, Integer quantityInStock) {
		this.books = books;
		this.libraries = libraries;
		this.quantityInStock = quantityInStock;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "books_has_librariesid", unique = true, nullable = false)
	public Integer getBooksHasLibrariesid() {
		return this.booksHasLibrariesid;
	}

	public void setBooksHasLibrariesid(Integer booksHasLibrariesid) {
		this.booksHasLibrariesid = booksHasLibrariesid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "isbn", nullable = false)
	public Books getBooks() {
		return this.books;
	}

	public void setBooks(Books books) {
		this.books = books;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "library_id", nullable = false)
	public Libraries getLibraries() {
		return this.libraries;
	}

	public void setLibraries(Libraries libraries) {
		this.libraries = libraries;
	}

	@Column(name = "quantity_in_stock")
	public Integer getQuantityInStock() {
		return this.quantityInStock;
	}

	public void setQuantityInStock(Integer quantityInStock) {
		this.quantityInStock = quantityInStock;
	}

}
