package com.example.demo;
// Generated Sep 28, 2018 9:42:18 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "categories", catalog = "librares")
public class Categories implements java.io.Serializable {

	private Integer categoryId;
	private String categoryName;
	private Set booksByCategories = new HashSet(0);

	public Categories() {
	}

	public Categories(String categoryName, Set booksByCategories) {
		this.categoryName = categoryName;
		this.booksByCategories = booksByCategories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "category_id", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "category_name", length = 45)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categories")
	public Set getBooksByCategories() {
		return this.booksByCategories;
	}

	public void setBooksByCategories(Set booksByCategories) {
		this.booksByCategories = booksByCategories;
	}

}
