/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service.criteria;

/**
 * Criteria bean used for Addresses search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class AddressesCriteria {

    private String line1NumberBuilding; 
    private String line2NumberStreest; 
    private String line3AreaLocality; 
    private String city; 
    private String zipPostcode; 
    private String stateProviceCounty; 
    private String country; 
    private String ortherAddressDetails; 
	// Constructor
	public AddressesCriteria() {
		// Needed empty constructor for serialization
	}

	public void setLine1NumberBuilding(String line1NumberBuilding) {this.line1NumberBuilding = line1NumberBuilding;}
	public String getLine1NumberBuilding() {return this.line1NumberBuilding;}
	public void setLine2NumberStreest(String line2NumberStreest) {this.line2NumberStreest = line2NumberStreest;}
	public String getLine2NumberStreest() {return this.line2NumberStreest;}
	public void setLine3AreaLocality(String line3AreaLocality) {this.line3AreaLocality = line3AreaLocality;}
	public String getLine3AreaLocality() {return this.line3AreaLocality;}
	public void setCity(String city) {this.city = city;}
	public String getCity() {return this.city;}
	public void setZipPostcode(String zipPostcode) {this.zipPostcode = zipPostcode;}
	public String getZipPostcode() {return this.zipPostcode;}
	public void setStateProviceCounty(String stateProviceCounty) {this.stateProviceCounty = stateProviceCounty;}
	public String getStateProviceCounty() {return this.stateProviceCounty;}
	public void setCountry(String country) {this.country = country;}
	public String getCountry() {return this.country;}
	public void setOrtherAddressDetails(String ortherAddressDetails) {this.ortherAddressDetails = ortherAddressDetails;}
	public String getOrtherAddressDetails() {return this.ortherAddressDetails;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(line1NumberBuilding); 
		sb.append("|"); 
		sb.append(line2NumberStreest); 
		sb.append("|"); 
		sb.append(line3AreaLocality); 
		sb.append("|"); 
		sb.append(city); 
		sb.append("|"); 
		sb.append(zipPostcode); 
		sb.append("|"); 
		sb.append(stateProviceCounty); 
		sb.append("|"); 
		sb.append(country); 
		sb.append("|"); 
		sb.append(ortherAddressDetails); 
        return sb.toString();
	}
}
