/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service.criteria;

/**
 * Criteria bean used for AnazoneBook search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class AnazoneBookCriteria {

    private String title; 
    private String dataOfPublication; 
    private String amazoneStarRating; 
    private String listPrice; 
    private String amazoePrice; 
    private String yourSaving; 
	// Constructor
	public AnazoneBookCriteria() {
		// Needed empty constructor for serialization
	}

	public void setTitle(String title) {this.title = title;}
	public String getTitle() {return this.title;}
	public void setDataOfPublication(String dataOfPublication) {this.dataOfPublication = dataOfPublication;}
	public String getDataOfPublication() {return this.dataOfPublication;}
	public void setAmazoneStarRating(String amazoneStarRating) {this.amazoneStarRating = amazoneStarRating;}
	public String getAmazoneStarRating() {return this.amazoneStarRating;}
	public void setListPrice(String listPrice) {this.listPrice = listPrice;}
	public String getListPrice() {return this.listPrice;}
	public void setAmazoePrice(String amazoePrice) {this.amazoePrice = amazoePrice;}
	public String getAmazoePrice() {return this.amazoePrice;}
	public void setYourSaving(String yourSaving) {this.yourSaving = yourSaving;}
	public String getYourSaving() {return this.yourSaving;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(title); 
		sb.append("|"); 
		sb.append(dataOfPublication); 
		sb.append("|"); 
		sb.append(amazoneStarRating); 
		sb.append("|"); 
		sb.append(listPrice); 
		sb.append("|"); 
		sb.append(amazoePrice); 
		sb.append("|"); 
		sb.append(yourSaving); 
        return sb.toString();
	}
}
