/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service.criteria;

/**
 * Criteria bean used for Libraries search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class LibrariesCriteria {

    private String libraryName; 
    private String libraryDetails; 
	// Constructor
	public LibrariesCriteria() {
		// Needed empty constructor for serialization
	}

	public void setLibraryName(String libraryName) {this.libraryName = libraryName;}
	public String getLibraryName() {return this.libraryName;}
	public void setLibraryDetails(String libraryDetails) {this.libraryDetails = libraryDetails;}
	public String getLibraryDetails() {return this.libraryDetails;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(libraryName); 
		sb.append("|"); 
		sb.append(libraryDetails); 
        return sb.toString();
	}
}
