/*
 * Created on 2018-09-28 ( Date ISO 2018-09-28 - Time 09:53:16 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.repository;

import com.example.demo.entity.AmazoneBooks;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for AmazoneBooks.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface AmazoneBooksRepository  extends JpaRepository<AmazoneBooks, Long>, JpaSpecificationExecutor<AmazoneBooks> {
	
	AmazoneBooks findByIsbn(Long isbn);
}