package com.example.demo.entity;
// Generated Oct 2, 2018 5:55:30 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AmazonBook generated by hbm2java
 */
@Entity
@Table(name = "amazon_book", catalog = "libraries")
public class AmazonBook implements java.io.Serializable {

	private Integer isbn;
	private String title;
	private String author;
	private Date dataOfPublication;
	private Boolean publicsher;
	private String listPrice;
	private String amazonPrice;
	private String yourSaving;

	public AmazonBook() {
	}

	public AmazonBook(String title, String author, Date dataOfPublication, Boolean publicsher, String listPrice,
			String amazonPrice, String yourSaving) {
		this.title = title;
		this.author = author;
		this.dataOfPublication = dataOfPublication;
		this.publicsher = publicsher;
		this.listPrice = listPrice;
		this.amazonPrice = amazonPrice;
		this.yourSaving = yourSaving;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "isbn", unique = true, nullable = false)
	public Integer getIsbn() {
		return this.isbn;
	}

	public void setIsbn(Integer isbn) {
		this.isbn = isbn;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "author", length = 45)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_of_publication", length = 10)
	public Date getDataOfPublication() {
		return this.dataOfPublication;
	}

	public void setDataOfPublication(Date dataOfPublication) {
		this.dataOfPublication = dataOfPublication;
	}

	@Column(name = "publicsher")
	public Boolean getPublicsher() {
		return this.publicsher;
	}

	public void setPublicsher(Boolean publicsher) {
		this.publicsher = publicsher;
	}

	@Column(name = "list_price", length = 45)
	public String getListPrice() {
		return this.listPrice;
	}

	public void setListPrice(String listPrice) {
		this.listPrice = listPrice;
	}

	@Column(name = "amazon_price", length = 45)
	public String getAmazonPrice() {
		return this.amazonPrice;
	}

	public void setAmazonPrice(String amazonPrice) {
		this.amazonPrice = amazonPrice;
	}

	@Column(name = "your_saving", length = 45)
	public String getYourSaving() {
		return this.yourSaving;
	}

	public void setYourSaving(String yourSaving) {
		this.yourSaving = yourSaving;
	}

}
