package com.example.demo.entity;
// Generated Oct 2, 2018 5:55:30 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import net.minidev.json.annotate.JsonIgnore;

/**
 * Author generated by hbm2java
 */
@Entity
@Table(name = "author", catalog = "libraries")
public class Author implements java.io.Serializable {

	private Integer authorId;
	private String authorFirstName;
	private String authorLastName;
	@com.fasterxml.jackson.annotation.JsonIgnore
	private Set<Books> bookses = new HashSet<Books>(0);

	public Author() {
	}

	public Author(String authorFirstName, String authorLastName, Set<Books> bookses) {
		this.authorFirstName = authorFirstName;
		this.authorLastName = authorLastName;
		this.bookses = bookses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "author_id", unique = true, nullable = false)
	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	@Column(name = "author_first_name", length = 45)
	public String getAuthorFirstName() {
		return this.authorFirstName;
	}

	public void setAuthorFirstName(String authorFirstName) {
		this.authorFirstName = authorFirstName;
	}

	@Column(name = "author_last_name", length = 45)
	public String getAuthorLastName() {
		return this.authorLastName;
	}

	public void setAuthorLastName(String authorLastName) {
		this.authorLastName = authorLastName;
	}
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "book_by_author", catalog = "libraries", joinColumns = {
			@JoinColumn(name = "author_author_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "books_isbn", nullable = false, updatable = false) })
	public Set<Books> getBookses() {
		return this.bookses;
	}

	public void setBookses(Set<Books> bookses) {
		this.bookses = bookses;
	}

}
