package com.example.demo.entity;
// Generated Oct 2, 2018 5:55:30 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import net.minidev.json.annotate.JsonIgnore;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "categories", catalog = "libraries")
public class Categories implements java.io.Serializable {

	private int categoryId;
	private String categoryName;
	@com.fasterxml.jackson.annotation.JsonIgnore
	private Set<Books> bookses = new HashSet<Books>(0);

	public Categories() {
	}

	public Categories(int categoryId) {
		this.categoryId = categoryId;
	}

	public Categories(int categoryId, String categoryName, Set<Books> bookses) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.bookses = bookses;
	}

	@Id
	@Column(name = "category_id", unique = true, nullable = false)
	@GeneratedValue
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "category_name", length = 45)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}
	@JsonIgnore
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "book_by_category", catalog = "libraries", joinColumns = {
			@JoinColumn(name = "categories_category_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "books_isbn", nullable = false, updatable = false) })
	public Set<Books> getBookses() {
		return this.bookses;
	}

	public void setBookses(Set<Books> bookses) {
		this.bookses = bookses;
	}

}
