package com.example.demo.entity;
// Generated Oct 2, 2018 5:55:30 AM by Hibernate Tools 5.2.10.Final

import static javax.persistence.GenerationType.IDENTITY;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Libraries generated by hbm2java
 */
@Entity
@Table(name = "libraries", catalog = "libraries")
public class Libraries implements java.io.Serializable {

	private int libraryId;
	private String libraryName;
	private String ortherLibraryDetail;

	private Set<BooksHasLibraries> booksHasLibrarieses = new HashSet<BooksHasLibraries>(0);

	public Libraries() {
	}

	public Libraries(int libraryId) {
		this.libraryId = libraryId;
	}

	public Libraries(int libraryId, String libraryName, String ortherLibraryDetail,
			Set<BooksHasLibraries> booksHasLibrarieses) {
		this.libraryId = libraryId;
		this.libraryName = libraryName;
		this.ortherLibraryDetail = ortherLibraryDetail;
		this.booksHasLibrarieses = booksHasLibrarieses;
	}

	@Id
	@Column(name = "library_id", unique = true, nullable = false)
	@GeneratedValue(strategy = IDENTITY)
	public int getLibraryId() {
		return this.libraryId;
	}

	public void setLibraryId(int libraryId) {
		this.libraryId = libraryId;
	}

	@Column(name = "library_name", length = 45)
	public String getLibraryName() {
		return this.libraryName;
	}

	public void setLibraryName(String libraryName) {
		this.libraryName = libraryName;
	}

	@Column(name = "orther_library_detail", length = 45)
	public String getOrtherLibraryDetail() {
		return this.ortherLibraryDetail;
	}

	public void setOrtherLibraryDetail(String ortherLibraryDetail) {
		this.ortherLibraryDetail = ortherLibraryDetail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "libraries")
	public Set<BooksHasLibraries> getBooksHasLibrarieses() {
		return this.booksHasLibrarieses;
	}

	public void setBooksHasLibrarieses(Set<BooksHasLibraries> booksHasLibrarieses) {
		this.booksHasLibrarieses = booksHasLibrarieses;
	}

}
