/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for Addresses entity stored in table addresses.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="addresses", catalog="liberaries" )
public class Addresses implements Serializable {

	private static final Long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="address_id", nullable=false)
    private Long addressId ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="line_1_number_building", length=45)
    private String line1NumberBuilding ;     @Column(name="line_2_number_streest", length=45)
    private String line2NumberStreest ;     @Column(name="line_3_area_locality", length=45)
    private String line3AreaLocality ;     @Column(name="city", length=45)
    private String city ;     @Column(name="zip_postcode", length=45)
    private String zipPostcode ;     @Column(name="state_provice_county", length=45)
    private String stateProviceCounty ;     @Column(name="country", length=45)
    private String country ;     @Column(name="orther_address_details", length=45)
    private String ortherAddressDetails ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Addresses() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setAddressId(Long addressId) {
        this.addressId = addressId ;
    }
	public Long getAddressId() {
        return this.addressId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : line_1_number_building (VARCHAR) 
	public void setLine1NumberBuilding(String line1NumberBuilding) {this.line1NumberBuilding = line1NumberBuilding;}
	public String getLine1NumberBuilding() {return this.line1NumberBuilding;}

	//--- DATABASE MAPPING : line_2_number_streest (VARCHAR) 
	public void setLine2NumberStreest(String line2NumberStreest) {this.line2NumberStreest = line2NumberStreest;}
	public String getLine2NumberStreest() {return this.line2NumberStreest;}

	//--- DATABASE MAPPING : line_3_area_locality (VARCHAR) 
	public void setLine3AreaLocality(String line3AreaLocality) {this.line3AreaLocality = line3AreaLocality;}
	public String getLine3AreaLocality() {return this.line3AreaLocality;}

	//--- DATABASE MAPPING : city (VARCHAR) 
	public void setCity(String city) {this.city = city;}
	public String getCity() {return this.city;}

	//--- DATABASE MAPPING : zip_postcode (VARCHAR) 
	public void setZipPostcode(String zipPostcode) {this.zipPostcode = zipPostcode;}
	public String getZipPostcode() {return this.zipPostcode;}

	//--- DATABASE MAPPING : state_provice_county (VARCHAR) 
	public void setStateProviceCounty(String stateProviceCounty) {this.stateProviceCounty = stateProviceCounty;}
	public String getStateProviceCounty() {return this.stateProviceCounty;}

	//--- DATABASE MAPPING : country (VARCHAR) 
	public void setCountry(String country) {this.country = country;}
	public String getCountry() {return this.country;}

	//--- DATABASE MAPPING : orther_address_details (VARCHAR) 
	public void setOrtherAddressDetails(String ortherAddressDetails) {this.ortherAddressDetails = ortherAddressDetails;}
	public String getOrtherAddressDetails() {return this.ortherAddressDetails;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(addressId); 
		sb.append(line1NumberBuilding); 
		sb.append("|"); 
		sb.append(line2NumberStreest); 
		sb.append("|"); 
		sb.append(line3AreaLocality); 
		sb.append("|"); 
		sb.append(city); 
		sb.append("|"); 
		sb.append(zipPostcode); 
		sb.append("|"); 
		sb.append(stateProviceCounty); 
		sb.append("|"); 
		sb.append(country); 
		sb.append("|"); 
		sb.append(ortherAddressDetails); 
        return sb.toString();
    }
}