/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for Authors entity stored in table authors.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="authors", catalog="liberaries" )
public class Authors implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="author_id", nullable=false)
    private Long authorId ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="author_first_name", length=45)
    private String authorFirstName ;     @Column(name="author_last_name", length=45)
    private String authorLastName ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Authors() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setAuthorId(Long authorId) {
        this.authorId = authorId ;
    }
	public Long getAuthorId() {
        return this.authorId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : author_first_name (VARCHAR) 
	public void setAuthorFirstName(String authorFirstName) {this.authorFirstName = authorFirstName;}
	public String getAuthorFirstName() {return this.authorFirstName;}

	//--- DATABASE MAPPING : author_last_name (VARCHAR) 
	public void setAuthorLastName(String authorLastName) {this.authorLastName = authorLastName;}
	public String getAuthorLastName() {return this.authorLastName;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(authorId); 
		sb.append(authorFirstName); 
		sb.append("|"); 
		sb.append(authorLastName); 
        return sb.toString();
    }
}