/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Composite primary key for entity "BookAtLibraries" ( stored in table "book_at_libraries" )
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
 @Embeddable
public class BookAtLibrariesKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="library_id", nullable=false)
    private Long libraryId ;
    @Column(name="isbn", nullable=false)
    private Long isbn ;

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public BookAtLibrariesKey() {
        super();
    }

    public BookAtLibrariesKey(Long libraryId, Long isbn) {
        super();
        this.libraryId = libraryId ;
        this.isbn = isbn ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
	public void setLibraryId(Long value) {
        this.libraryId = value;
    }
	public Long getLibraryId() {
        return this.libraryId;
    }

	public void setIsbn(Long value) {
        this.isbn = value;
    }
	public Long getIsbn() {
        return this.isbn;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(libraryId); 
		sb.append("|"); 
		sb.append(isbn); 
        return sb.toString();
    }
}
