/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Composite primary key for entity "BooksByCategories" ( stored in table "books_by_categories" )
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
 @Embeddable
public class BooksByCategoriesKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="isbn", nullable=false)
    private Long isbn ;
    @Column(name="caregory_id", nullable=false)
    private Long caregoryId ;

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public BooksByCategoriesKey() {
        super();
    }

    public BooksByCategoriesKey(Long isbn, Long caregoryId) {
        super();
        this.isbn = isbn ;
        this.caregoryId = caregoryId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
	public void setIsbn(Long value) {
        this.isbn = value;
    }
	public Long getIsbn() {
        return this.isbn;
    }

	public void setCaregoryId(Long value) {
        this.caregoryId = value;
    }
	public Long getCaregoryId() {
        return this.caregoryId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(isbn); 
		sb.append("|"); 
		sb.append(caregoryId); 
        return sb.toString();
    }
}
