/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Composite primary key for entity "BooksByAuthor" ( stored in table "books_by_author" )
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
 @Embeddable
public class BooksByAuthorKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="authors_author_id", nullable=false)
    private Long authorsAuthorId ;
    @Column(name="books_isbn", nullable=false)
    private Long booksIsbn ;

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public BooksByAuthorKey() {
        super();
    }

    public BooksByAuthorKey(Long authorsAuthorId, Long booksIsbn) {
        super();
        this.authorsAuthorId = authorsAuthorId ;
        this.booksIsbn = booksIsbn ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
	public void setAuthorsAuthorId(Long value) {
        this.authorsAuthorId = value;
    }
	public Long getAuthorsAuthorId() {
        return this.authorsAuthorId;
    }

	public void setBooksIsbn(Long value) {
        this.booksIsbn = value;
    }
	public Long getBooksIsbn() {
        return this.booksIsbn;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(authorsAuthorId); 
		sb.append("|"); 
		sb.append(booksIsbn); 
        return sb.toString();
    }
}
