/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * Persistent class for Books entity stored in table books.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="books", catalog="liberaries" )
public class Books implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="isbn", nullable=false)
    private Long isbn ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="book_title", length=45)
    private String bookTitle ;     @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_of_publication")
    private Date dataOfPublication ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Books() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setIsbn(Long isbn) {
        this.isbn = isbn ;
    }
	public Long getIsbn() {
        return this.isbn;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : book_title (VARCHAR) 
	public void setBookTitle(String bookTitle) {this.bookTitle = bookTitle;}
	public String getBookTitle() {return this.bookTitle;}

	//--- DATABASE MAPPING : data_of_publication (DATETIME) 
	public void setDataOfPublication(Date dataOfPublication) {this.dataOfPublication = dataOfPublication;}
	public Date getDataOfPublication() {return this.dataOfPublication;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(isbn); 
		sb.append(bookTitle); 
		sb.append("|"); 
		sb.append(dataOfPublication); 
        return sb.toString();
    }
}