/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.entity;


import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for BooksByCategories entity stored in table books_by_categories.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="books_by_categories", catalog="liberaries" )
public class BooksByCategories implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private BooksByCategoriesKey compositePrimaryKey ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public BooksByCategories() {
		super();
		this.compositePrimaryKey = new BooksByCategoriesKey();       
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setIsbn(Long isbn) {
        this.compositePrimaryKey.setIsbn(isbn) ;
    }
	public Long getIsbn() {
        return this.compositePrimaryKey.getIsbn() ;
    }
	public void setCaregoryId(Long caregoryId) {
        this.compositePrimaryKey.setCaregoryId(caregoryId) ;
    }
	public Long getCaregoryId() {
        return this.compositePrimaryKey.getCaregoryId() ;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append("[" + compositePrimaryKey + "]"); 
        return sb.toString();
    }
}