/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.entity;


import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for BooksByAuthor entity stored in table books_by_author.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="books_by_author", catalog="liberaries" )
public class BooksByAuthor implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private BooksByAuthorKey compositePrimaryKey ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public BooksByAuthor() {
		super();
		this.compositePrimaryKey = new BooksByAuthorKey();       
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setAuthorsAuthorId(Long authorsAuthorId) {
        this.compositePrimaryKey.setAuthorsAuthorId(authorsAuthorId) ;
    }
	public Long getAuthorsAuthorId() {
        return this.compositePrimaryKey.getAuthorsAuthorId() ;
    }
	public void setBooksIsbn(Long booksIsbn) {
        this.compositePrimaryKey.setBooksIsbn(booksIsbn) ;
    }
	public Long getBooksIsbn() {
        return this.compositePrimaryKey.getBooksIsbn() ;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append("[" + compositePrimaryKey + "]"); 
        return sb.toString();
    }
}