/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for Libraries entity stored in table libraries.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="libraries", catalog="liberaries" )
public class Libraries implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="library_id", nullable=false)
    private Long libraryId ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="library_name", length=45)
    private String libraryName ;     @Column(name="library_details", length=45)
    private String libraryDetails ;     @Column(name="address_id", nullable=false)
    private Long addressId ; // Foreign Key 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Libraries() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setLibraryId(Long libraryId) {
        this.libraryId = libraryId ;
    }
	public Long getLibraryId() {
        return this.libraryId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : library_name (VARCHAR) 
	public void setLibraryName(String libraryName) {this.libraryName = libraryName;}
	public String getLibraryName() {return this.libraryName;}

	//--- DATABASE MAPPING : library_details (VARCHAR) 
	public void setLibraryDetails(String libraryDetails) {this.libraryDetails = libraryDetails;}
	public String getLibraryDetails() {return this.libraryDetails;}

	//--- DATABASE MAPPING : address_id (INT) 
	public void setAddressId(Long addressId) {this.addressId = addressId;}
	public Long getAddressId() {return this.addressId;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(libraryId); 
		sb.append(libraryName); 
		sb.append("|"); 
		sb.append(libraryDetails); 
		sb.append("|"); 
		sb.append(addressId); 
        return sb.toString();
    }
}