/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for MembersRequest entity stored in table members_request.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="members_request", catalog="liberaries" )
public class MembersRequest implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="request_id", nullable=false)
    private Long requestId ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="members_member_id", nullable=false)
    private Long membersMemberId ; // Foreign Key     @Column(name="books_isbn", nullable=false)
    private Long booksIsbn ; // Foreign Key     @Column(name="data_requested", length=45)
    private String dataRequested ;     @Column(name="date_located", length=45)
    private String dateLocated ;     @Column(name="otherrequest_details", length=45)
    private String otherrequestDetails ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public MembersRequest() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setRequestId(Long requestId) {
        this.requestId = requestId ;
    }
	public Long getRequestId() {
        return this.requestId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : members_member_id (INT) 
	public void setMembersMemberId(Long membersMemberId) {this.membersMemberId = membersMemberId;}
	public Long getMembersMemberId() {return this.membersMemberId;}

	//--- DATABASE MAPPING : books_isbn (INT) 
	public void setBooksIsbn(Long booksIsbn) {this.booksIsbn = booksIsbn;}
	public Long getBooksIsbn() {return this.booksIsbn;}

	//--- DATABASE MAPPING : data_requested (VARCHAR) 
	public void setDataRequested(String dataRequested) {this.dataRequested = dataRequested;}
	public String getDataRequested() {return this.dataRequested;}

	//--- DATABASE MAPPING : date_located (VARCHAR) 
	public void setDateLocated(String dateLocated) {this.dateLocated = dateLocated;}
	public String getDateLocated() {return this.dateLocated;}

	//--- DATABASE MAPPING : otherrequest_details (VARCHAR) 
	public void setOtherrequestDetails(String otherrequestDetails) {this.otherrequestDetails = otherrequestDetails;}
	public String getOtherrequestDetails() {return this.otherrequestDetails;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(requestId); 
		sb.append(membersMemberId); 
		sb.append("|"); 
		sb.append(booksIsbn); 
		sb.append("|"); 
		sb.append(dataRequested); 
		sb.append("|"); 
		sb.append(dateLocated); 
		sb.append("|"); 
		sb.append(otherrequestDetails); 
        return sb.toString();
    }
}