/*
 * Created on 2018-09-28 ( Date ISO 2018-09-28 - Time 09:53:16 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import org.apache.commons.lang3.StringUtils;
import com.example.demo.entity.Addresses;
import com.example.demo.repository.AddressesRepository;
import com.example.demo.service.criteria.AddressesCriteria;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;

/**
 * Service implementation for Addresses.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Service
public class AddressesServiceImpl implements AddressesService {

	@Autowired
	private AddressesRepository addressesRepository;

	@Override
	public Page<Addresses> search(Pageable pageable, AddressesCriteria criteria) {
		return addressesRepository.findAll(new AddressesSpecification(criteria), pageable);
	}

	@Override
	public Addresses get(Long addressId) {
		return addressesRepository.findByAddressId(addressId);
	}

	@Override
	public Boolean delete(Long addressId) {
		if (addressesRepository.findByAddressId(addressId) != null) {
			addressesRepository.deleteById(addressId);
			return true;
		}
		return false;
	}

	@Override
	public Addresses create(Addresses addresses) {
		return addressesRepository.save(addresses);
	}

	@Override
	public Boolean save(Addresses addresses) {
		final Long pk = addresses.getAddressId();
		if (addressesRepository.findByAddressId(pk) != null) {
			addressesRepository.save(addresses);
			return true;
		}
		return false;
	}

	@Override
	public Boolean exist(Addresses addresses) {
		return addressesRepository.existsById(addresses.getAddressId());
	}

	class AddressesSpecification implements Specification<Addresses> {

		private AddressesCriteria criteria;

		public AddressesSpecification(AddressesCriteria criteria) {
			this.criteria = criteria;
		}

	

		private Predicate andTogether(List<Predicate> predicates, CriteriaBuilder builder) {
			return builder.and(predicates.toArray(new Predicate[0]));
		}



		@Override
		public Predicate toPredicate(Root<Addresses> arg0, CriteriaQuery<?> arg1, CriteriaBuilder arg2) {
			// TODO Auto-generated method stub
			return null;
		}
	}

	@Override
	public List<Addresses> getAll() {
		// TODO Auto-generated method stub
		return addressesRepository.findAll();
	}

}
