/*
 * Created on 2018-09-28 ( Date ISO 2018-09-28 - Time 09:53:16 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.AmazoneBooks;
import com.example.demo.service.criteria.AmazoneBooksCriteria;

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Service interface for AmazoneBooks.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public interface AmazoneBooksService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @param criteria filters
	 * @return a page of amazoneBooks
	 */
	public Page<AmazoneBooks> search(Pageable pageable, AmazoneBooksCriteria criteria);
	/**
	 * Recover an amazoneBooks following an id.
	 * @param id the given id
	 * @return the amazoneBooks
	 */
	public AmazoneBooks get(Long isbn);

	/**
	 * Perform an amazoneBooks deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(Long isbn);

	/**
	 * Perform an amazoneBooks creation.
	 * @param amazoneBooks to create
	 * @return created amazoneBooks
	 */
	public AmazoneBooks create(AmazoneBooks amazoneBooks);

	/**
	 * Perform an amazoneBooks update.
	 * @param amazoneBooks to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(AmazoneBooks amazoneBooks);

	/**
	 * Test amazoneBooks existence.
	 * @param amazoneBooks to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(AmazoneBooks amazoneBooks);
	
	public List<AmazoneBooks> getAll();
}
