/*
 * Created on 2018-09-28 ( Date ISO 2018-09-28 - Time 09:53:16 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.Authors;
import com.example.demo.service.criteria.AuthorsCriteria;

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Service interface for Authors.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public interface AuthorsService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @param criteria filters
	 * @return a page of authors
	 */
	public Page<Authors> search(Pageable pageable, AuthorsCriteria criteria);
	/**
	 * Recover an authors following an id.
	 * @param id the given id
	 * @return the authors
	 */
	public Authors get(Long authorId);

	/**
	 * Perform an authors deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(Long authorId);

	/**
	 * Perform an authors creation.
	 * @param authors to create
	 * @return created authors
	 */
	public Authors create(Authors authors);

	/**
	 * Perform an authors update.
	 * @param authors to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(Authors authors);

	/**
	 * Test authors existence.
	 * @param authors to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(Authors authors);
	
	List<Authors> findAll();
}
