/*
 * Created on 2018-09-28 ( Date ISO 2018-09-28 - Time 09:53:16 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;
import com.example.demo.entity.BooksByAuthor;
import com.example.demo.repository.BooksByAuthorRepository;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
 * Service implementation for BooksByAuthor.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Service
public class BooksByAuthorServiceImpl implements BooksByAuthorService {

	@Autowired
	private BooksByAuthorRepository booksByAuthorRepository;

	@Override
	public Page<BooksByAuthor> search(Pageable pageable) {
		return booksByAuthorRepository.findAll(pageable);
	}

	@Override
	public BooksByAuthor get(Long booksHasAuthorsid) {
		return booksByAuthorRepository.findByBooksHasAuthorsid(booksHasAuthorsid);
	}

	@Override
	public Boolean delete(Long booksHasAuthorsid) {
		if (booksByAuthorRepository.findByBooksHasAuthorsid(booksHasAuthorsid) != null) {
			booksByAuthorRepository.deleteById(booksHasAuthorsid);
			return true;
		}
		return false;
	}

	@Override
	public BooksByAuthor create(BooksByAuthor booksByAuthor) {
		return booksByAuthorRepository.save(booksByAuthor);
	}

	@Override
	public Boolean save(BooksByAuthor booksByAuthor) {
		final Long pk = booksByAuthor.getBooksHasAuthorsid();
		if (booksByAuthorRepository.findByBooksHasAuthorsid(pk) != null) {
			booksByAuthorRepository.save(booksByAuthor);
			return true;
		}
		return false;
	}

	@Override
	public Boolean exist(BooksByAuthor booksByAuthor) {
		return booksByAuthorRepository.existsById(booksByAuthor.getBooksHasAuthorsid());
	}

	@Override
	public List<BooksByAuthor> getAll() {
		// TODO Auto-generated method stub
		return booksByAuthorRepository.findAll();
	}


}
