/*
 * Created on 2018-09-28 ( Date ISO 2018-09-28 - Time 09:53:16 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service.criteria;

/**
 * Criteria bean used for Addresses search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class AddressesCriteria {

    private String line1NumberBuilding; 
    private String line2NumberStreet; 
    private String line3areaLocality; 
    private String city; 
    private String zipPostcode; 
    private String stateProvicenCounty; 
    private String country; 
    private String otherAddressDetails; 
	// Constructor
	public AddressesCriteria() {
		// Needed empty constructor for serialization
	}

	public void setLine1NumberBuilding(String line1NumberBuilding) {this.line1NumberBuilding = line1NumberBuilding;}
	public String getLine1NumberBuilding() {return this.line1NumberBuilding;}
	public void setLine2NumberStreet(String line2NumberStreet) {this.line2NumberStreet = line2NumberStreet;}
	public String getLine2NumberStreet() {return this.line2NumberStreet;}
	public void setLine3areaLocality(String line3areaLocality) {this.line3areaLocality = line3areaLocality;}
	public String getLine3areaLocality() {return this.line3areaLocality;}
	public void setCity(String city) {this.city = city;}
	public String getCity() {return this.city;}
	public void setZipPostcode(String zipPostcode) {this.zipPostcode = zipPostcode;}
	public String getZipPostcode() {return this.zipPostcode;}
	public void setStateProvicenCounty(String stateProvicenCounty) {this.stateProvicenCounty = stateProvicenCounty;}
	public String getStateProvicenCounty() {return this.stateProvicenCounty;}
	public void setCountry(String country) {this.country = country;}
	public String getCountry() {return this.country;}
	public void setOtherAddressDetails(String otherAddressDetails) {this.otherAddressDetails = otherAddressDetails;}
	public String getOtherAddressDetails() {return this.otherAddressDetails;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(line1NumberBuilding); 
		sb.append("|"); 
		sb.append(line2NumberStreet); 
		sb.append("|"); 
		sb.append(line3areaLocality); 
		sb.append("|"); 
		sb.append(city); 
		sb.append("|"); 
		sb.append(zipPostcode); 
		sb.append("|"); 
		sb.append(stateProvicenCounty); 
		sb.append("|"); 
		sb.append(country); 
		sb.append("|"); 
		sb.append(otherAddressDetails); 
        return sb.toString();
	}
}
