/*
 * Created on 2018-09-28 ( Date ISO 2018-09-28 - Time 09:53:16 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service.criteria;

/**
 * Criteria bean used for AmazoneBooks search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class AmazoneBooksCriteria {

    private String title; 
    private String authors; 
    private String amazonStartRating; 
    private String lishPrice; 
    private String yourSaving; 
	// Constructor
	public AmazoneBooksCriteria() {
		// Needed empty constructor for serialization
	}

	public void setTitle(String title) {this.title = title;}
	public String getTitle() {return this.title;}
	public void setAuthors(String authors) {this.authors = authors;}
	public String getAuthors() {return this.authors;}
	public void setAmazonStartRating(String amazonStartRating) {this.amazonStartRating = amazonStartRating;}
	public String getAmazonStartRating() {return this.amazonStartRating;}
	public void setLishPrice(String lishPrice) {this.lishPrice = lishPrice;}
	public String getLishPrice() {return this.lishPrice;}
	public void setYourSaving(String yourSaving) {this.yourSaving = yourSaving;}
	public String getYourSaving() {return this.yourSaving;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(title); 
		sb.append("|"); 
		sb.append(authors); 
		sb.append("|"); 
		sb.append(amazonStartRating); 
		sb.append("|"); 
		sb.append(lishPrice); 
		sb.append("|"); 
		sb.append(yourSaving); 
        return sb.toString();
	}
}
