/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service.criteria;

/**
 * Criteria bean used for Addresses search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class AddressesCriteria {

    private String line1NumberBulding; 
    private String line2NumberStreet; 
    private String line3AreaLocality; 
    private String city; 
    private String zipPostcode; 
    private String stateProvinceCountry; 
    private String country; 
    private String otherAddressDetail; 
	// Constructor
	public AddressesCriteria() {
		// Needed empty constructor for serialization
	}

	public void setLine1NumberBulding(String line1NumberBulding) {this.line1NumberBulding = line1NumberBulding;}
	public String getLine1NumberBulding() {return this.line1NumberBulding;}
	public void setLine2NumberStreet(String line2NumberStreet) {this.line2NumberStreet = line2NumberStreet;}
	public String getLine2NumberStreet() {return this.line2NumberStreet;}
	public void setLine3AreaLocality(String line3AreaLocality) {this.line3AreaLocality = line3AreaLocality;}
	public String getLine3AreaLocality() {return this.line3AreaLocality;}
	public void setCity(String city) {this.city = city;}
	public String getCity() {return this.city;}
	public void setZipPostcode(String zipPostcode) {this.zipPostcode = zipPostcode;}
	public String getZipPostcode() {return this.zipPostcode;}
	public void setStateProvinceCountry(String stateProvinceCountry) {this.stateProvinceCountry = stateProvinceCountry;}
	public String getStateProvinceCountry() {return this.stateProvinceCountry;}
	public void setCountry(String country) {this.country = country;}
	public String getCountry() {return this.country;}
	public void setOtherAddressDetail(String otherAddressDetail) {this.otherAddressDetail = otherAddressDetail;}
	public String getOtherAddressDetail() {return this.otherAddressDetail;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(line1NumberBulding); 
		sb.append("|"); 
		sb.append(line2NumberStreet); 
		sb.append("|"); 
		sb.append(line3AreaLocality); 
		sb.append("|"); 
		sb.append(city); 
		sb.append("|"); 
		sb.append(zipPostcode); 
		sb.append("|"); 
		sb.append(stateProvinceCountry); 
		sb.append("|"); 
		sb.append(country); 
		sb.append("|"); 
		sb.append(otherAddressDetail); 
        return sb.toString();
	}
}
