/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service.criteria;

/**
 * Criteria bean used for AmazonBook search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class AmazonBookCriteria {

    private String title; 
    private String author; 
    private String listPrice; 
    private String amazonPrice; 
    private String yourSaving; 
	// Constructor
	public AmazonBookCriteria() {
		// Needed empty constructor for serialization
	}

	public void setTitle(String title) {this.title = title;}
	public String getTitle() {return this.title;}
	public void setAuthor(String author) {this.author = author;}
	public String getAuthor() {return this.author;}
	public void setListPrice(String listPrice) {this.listPrice = listPrice;}
	public String getListPrice() {return this.listPrice;}
	public void setAmazonPrice(String amazonPrice) {this.amazonPrice = amazonPrice;}
	public String getAmazonPrice() {return this.amazonPrice;}
	public void setYourSaving(String yourSaving) {this.yourSaving = yourSaving;}
	public String getYourSaving() {return this.yourSaving;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(title); 
		sb.append("|"); 
		sb.append(author); 
		sb.append("|"); 
		sb.append(listPrice); 
		sb.append("|"); 
		sb.append(amazonPrice); 
		sb.append("|"); 
		sb.append(yourSaving); 
        return sb.toString();
	}
}
