/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service.criteria;

/**
 * Criteria bean used for BooksHasLibraries search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class BooksHasLibrariesCriteria {

    private String quatityInStock; 
	// Constructor
	public BooksHasLibrariesCriteria() {
		// Needed empty constructor for serialization
	}

	public void setQuatityInStock(String quatityInStock) {this.quatityInStock = quatityInStock;}
	public String getQuatityInStock() {return this.quatityInStock;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(quatityInStock); 
        return sb.toString();
	}
}
