/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service.criteria;

/**
 * Criteria bean used for MembersRequest search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class MembersRequestCriteria {

    private String ortherRequestDetail; 
	// Constructor
	public MembersRequestCriteria() {
		// Needed empty constructor for serialization
	}

	public void setOrtherRequestDetail(String ortherRequestDetail) {this.ortherRequestDetail = ortherRequestDetail;}
	public String getOrtherRequestDetail() {return this.ortherRequestDetail;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(ortherRequestDetail); 
        return sb.toString();
	}
}
