/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service.criteria;

/**
 * Criteria bean used for Members search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class MembersCriteria {

    private String gender; 
    private String memberFirstName; 
    private String memberLastName; 
    private String phoneNumber; 
    private String emailAddress; 
    private String ortherMemberDetail; 
	// Constructor
	public MembersCriteria() {
		// Needed empty constructor for serialization
	}

	public void setGender(String gender) {this.gender = gender;}
	public String getGender() {return this.gender;}
	public void setMemberFirstName(String memberFirstName) {this.memberFirstName = memberFirstName;}
	public String getMemberFirstName() {return this.memberFirstName;}
	public void setMemberLastName(String memberLastName) {this.memberLastName = memberLastName;}
	public String getMemberLastName() {return this.memberLastName;}
	public void setPhoneNumber(String phoneNumber) {this.phoneNumber = phoneNumber;}
	public String getPhoneNumber() {return this.phoneNumber;}
	public void setEmailAddress(String emailAddress) {this.emailAddress = emailAddress;}
	public String getEmailAddress() {return this.emailAddress;}
	public void setOrtherMemberDetail(String ortherMemberDetail) {this.ortherMemberDetail = ortherMemberDetail;}
	public String getOrtherMemberDetail() {return this.ortherMemberDetail;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(gender); 
		sb.append("|"); 
		sb.append(memberFirstName); 
		sb.append("|"); 
		sb.append(memberLastName); 
		sb.append("|"); 
		sb.append(phoneNumber); 
		sb.append("|"); 
		sb.append(emailAddress); 
		sb.append("|"); 
		sb.append(ortherMemberDetail); 
        return sb.toString();
	}
}
