/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import java.util.List;

import javax.transaction.Transactional;

import com.example.demo.entity.Addresses;
import com.example.demo.repository.AddressesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class AddressesServiceImpl implements AddressesService {

	@Autowired
	private AddressesRepository addressesRepository;

	@Override
	public Addresses getOne(Integer addressId) {
		return addressesRepository.findById(addressId).get();
	}

	@Override
	public Boolean delete(Integer addressId) {
		if (addressesRepository.getOne(addressId) != null) {
			addressesRepository.deleteById(addressId);
			return true;
		}
		return false;
	}

	@Override
	public Addresses create(Addresses addresses) {
		return addressesRepository.save(addresses);
	}

	@Override
	public Boolean update(Addresses addressesToUpdate) {
		Addresses addresses = addressesRepository.findByAddressId(addressesToUpdate.getAddressId());
		if(addresses!= null) {
			addressesRepository.save(addressesToUpdate);
			return true;
		}
		else
		return false;
	}

	@Override
	public Boolean exist(Addresses addresses) {
		return addressesRepository.existsById(addresses.getAddressId());
	}

	@Override
	public List<Addresses> findAll() {
		return addressesRepository.findAll();
	}

}
