/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.Addresses;
import java.util.List;

public interface AddressesService {

	Addresses getOne(Integer addressId);

	List<Addresses> findAll();

	Boolean delete(Integer addressId);

	Addresses create(Addresses addresses);

	Boolean update(Addresses addresses);

	Boolean exist(Addresses addresses);
}
