/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.AmazonBook;
import java.util.List;

public interface AmazonBookService {

	AmazonBook getOne(Integer isbn);

	List<AmazonBook> findAll();

	Boolean delete(Integer isbn);

	AmazonBook create(AmazonBook amazonBook);

	Boolean update(AmazonBook amazonBook);

	Boolean exist(AmazonBook amazonBook);
}

