/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import java.util.List;

import javax.transaction.Transactional;

import com.example.demo.entity.AmazonBook;
import com.example.demo.repository.AmazonBookRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class AmazonBookServiceImpl implements AmazonBookService {

	@Autowired
	private AmazonBookRepository amazonBookRepository;

	@Override
	public AmazonBook getOne(Integer isbn) {
		return amazonBookRepository.findById(isbn).get();
	}

	@Override
	public Boolean delete(Integer isbn) {
		if (amazonBookRepository.getOne(isbn) != null) {
			amazonBookRepository.deleteById(isbn);
			return true;
		}
		return false;
	}

	@Override
	public AmazonBook create(AmazonBook amazonBook) {
		return amazonBookRepository.save(amazonBook);
	}

	@Override
	public Boolean update(AmazonBook amazonBookToUpdate) {
		AmazonBook amazonBook = amazonBookRepository.findByIsbn(amazonBookToUpdate.getIsbn());
		if(amazonBook!=null)
		{
			amazonBookRepository.save(amazonBook);
			return true;
		}
		else
			return false;
	}

	@Override
	public Boolean exist(AmazonBook amazonBook) {
		return amazonBookRepository.existsById(amazonBook.getIsbn());
	}

	@Override
	public List<AmazonBook> findAll() {
		return amazonBookRepository.findAll();
	}

}
