/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import java.util.List;

import javax.transaction.Transactional;

import com.example.demo.entity.Author;
import com.example.demo.repository.AuthorRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class AuthorServiceImpl implements AuthorService {

	@Autowired
	private AuthorRepository authorRepository;

	@Override
	public Author getOne(Integer authorId) {
		return authorRepository.findById(authorId).get();
	}

	@Override
	public Boolean delete(Integer authorId) {
		if (authorRepository.getOne(authorId) != null) {
			authorRepository.deleteById(authorId);
			return true;
		}
		return false;
	}

	@Override
	public Author create(Author author) {
		return authorRepository.save(author);
	}

	@Override
	public Boolean update(Author authorToUpdate) {
		Author author = authorRepository.findByAuthorId(authorToUpdate.getAuthorId());
		if(author!=null)
		{
			authorRepository.save(authorToUpdate);
			return true;
		}
		else return false;
	}

	@Override
	public Boolean exist(Author author) {
		return authorRepository.existsById(author.getAuthorId());
	}

	@Override
	public List<Author> findAll() {
		return authorRepository.findAll();
	}

}
