/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.Author;
import java.util.List;

public interface AuthorService {

	Author getOne(Integer authorId);

	List<Author> findAll();

	Boolean delete(Integer authorId);

	Author create(Author author);

	Boolean update(Author author);

	Boolean exist(Author author);
}

