/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.Books;
import java.util.List;

public interface BooksService {

	Books getOne(Integer isbn);

	List<Books> findAll();

	Boolean delete(Integer isbn);

	Books create(Books books);

	Boolean update(Books books);

	Boolean exist(Books books);
}
