/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import java.util.List;

import javax.transaction.Transactional;

import com.example.demo.entity.Books;
import com.example.demo.repository.BooksRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class BooksServiceImpl implements BooksService {

	@Autowired
	private BooksRepository booksRepository;

	@Override
	public Books getOne(Integer isbn) {
		return booksRepository.findById(isbn).get();
	}

	@Override
	public Boolean delete(Integer isbn) {
		if (booksRepository.getOne(isbn) != null) {
			booksRepository.deleteById(isbn);
			return true;
		}
		return false;
	}

	@Override
	public Books create(Books books) {
		return booksRepository.save(books);
	}

	@Override
	public Boolean update(Books booksToUpdate) {
		Books books = booksRepository.findByIsbn(booksToUpdate.getIsbn());
		
		System.out.println(books);
			
		if(books !=null)
		{
			 booksRepository.save(booksToUpdate);
			 return true;
		}
		else
		return false;
	}

	@Override
	public Boolean exist(Books books) {
		return booksRepository.existsById(books.getIsbn());
	}

	@Override
	public List<Books> findAll() {
		return booksRepository.findAll();
	}

}
