/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.BooksHasLibraries;
import com.example.demo.entity.BooksHasLibrariesId;

import java.util.List;

public interface BooksHasLibrariesService {

	BooksHasLibraries getOne(BooksHasLibrariesId librariesLibraryId);

	List<BooksHasLibraries> findAll();

	Boolean delete(BooksHasLibrariesId librariesLibraryId);

	BooksHasLibraries create(BooksHasLibraries booksHasLibraries);

	Boolean update(BooksHasLibraries booksHasLibraries);

	Boolean exist(BooksHasLibraries booksHasLibraries);
}

