/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import java.util.List;

import javax.transaction.Transactional;

import com.example.demo.entity.Categories;
import com.example.demo.repository.CategoriesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class CategoriesServiceImpl implements CategoriesService {

	@Autowired
	private CategoriesRepository categoriesRepository;

	@Override
	public Categories getOne(Integer categoryId) {
		return categoriesRepository.findById(categoryId).get();
	}

	@Override
	public Boolean delete(Integer categoryId) {
		if (categoriesRepository.getOne(categoryId) != null) {
			categoriesRepository.deleteById(categoryId);
			return true;
		}
		return false;
	}

	@Override
	public Categories create(Categories categories) {
		return categoriesRepository.save(categories);
	}

	@Override
	public Boolean update(Categories categoriesToUpdate) {
		Categories categories = categoriesRepository.findByCategoryId(categoriesToUpdate.getCategoryId());
		if(categories!=null) {
			categoriesRepository.save(categories);
			return true;
		}else return false;
	}

	@Override
	public Boolean exist(Categories categories) {
		return categoriesRepository.existsById(categories.getCategoryId());
	}

	@Override
	public List<Categories> findAll() {
		return categoriesRepository.findAll();
	}

}
