/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.Libraries;
import java.util.List;

public interface LibrariesService {

	Libraries getOne(Integer libraryId);

	List<Libraries> findAll();

	Boolean delete(Integer libraryId);

	Libraries create(Libraries libraries);

	Boolean update(Libraries libraries);

	Boolean exist(Libraries libraries);
}
