/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import java.util.List;

import javax.transaction.Transactional;

import com.example.demo.entity.Libraries;
import com.example.demo.repository.LibrariesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class LibrariesServiceImpl implements LibrariesService {

	@Autowired
	private LibrariesRepository librariesRepository;

	@Override
	public Libraries getOne(Integer libraryId) {
		return librariesRepository.findById(libraryId).get();
	}

	@Override
	public Boolean delete(Integer libraryId) {
		if (librariesRepository.getOne(libraryId) != null) {
			librariesRepository.deleteById(libraryId);
			return true;
		}
		return false;
	}

	@Override
	public Libraries create(Libraries libraries) {
		return librariesRepository.save(libraries);
	}

	@Override
	public Boolean update(Libraries librariesToUpdate) {
		Libraries libraries = librariesRepository.findByLibraryId(librariesToUpdate.getLibraryId());
		if(libraries!=null){
			librariesRepository.save(librariesToUpdate);
			return true;
		}else return false;
	}

	@Override
	public Boolean exist(Libraries libraries) {
		return librariesRepository.existsById(libraries.getLibraryId());
	}

	@Override
	public List<Libraries> findAll() {
		return librariesRepository.findAll();
	}

}
