/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.Members;
import java.util.List;

import org.hibernate.hql.internal.ast.tree.BooleanLiteralNode;

public interface MembersService {

	Members getOne(Integer memberId);

	List<Members> findAll();

	Boolean delete(Integer memberId);

	Members create(Members members);

	Boolean update(Members members);

	Boolean exist(Members members);
}
