/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import com.example.demo.entity.MembersRequest;
import java.util.List;

public interface MembersRequestService {

	MembersRequest getOne(Integer requestId);

	List<MembersRequest> findAll();

	Boolean delete(Integer requestId);

	MembersRequest create(MembersRequest membersRequest);

	Boolean update(MembersRequest membersRequest);

	Boolean exist(MembersRequest membersRequest);
}
