/*
 * Created on 2018-10-02 ( Date ISO 2018-10-02 - Time 05:57:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import java.util.List;

import javax.transaction.Transactional;

import com.example.demo.entity.MembersRequest;
import com.example.demo.repository.MembersRequestRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class MembersRequestServiceImpl implements MembersRequestService {

	@Autowired
	private MembersRequestRepository membersRequestRepository;

	@Override
	public MembersRequest getOne(Integer requestId) {
		return membersRequestRepository.findById(requestId).get();
	}

	@Override
	public Boolean delete(Integer requestId) {
		if (membersRequestRepository.getOne(requestId) != null) {
			membersRequestRepository.deleteById(requestId);
			return true;
		}
		return false;
	}

	@Override
	public MembersRequest create(MembersRequest membersRequest) {
		return membersRequestRepository.save(membersRequest);
	}

	@Override
	public Boolean update(MembersRequest membersRequestToUpdate) {
		MembersRequest membersRequest = membersRequestRepository.findByRequestId(membersRequestToUpdate.getRequestId());
		if(membersRequest!=null)
		{
			 membersRequestRepository.save(membersRequest);
			 return true;
		}
		else return false;
	
	}

	@Override
	public Boolean exist(MembersRequest membersRequest) {
		return membersRequestRepository.existsById(membersRequest.getRequestId());
	}

	@Override
	public List<MembersRequest> findAll() {
		return membersRequestRepository.findAll();
	}

}
