/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;

import com.example.demo.entity.Addresses;
import com.example.demo.repository.AddressesRepository;
import com.example.demo.service.criteria.AddressesCriteria;

/**
 * Service implementation for Addresses.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Service
public class AddressesServiceImpl implements AddressesService {

	@Autowired
	private AddressesRepository addressesRepository;

	@Override
	public Page<Addresses> search(Pageable pageable, AddressesCriteria criteria) {
		return addressesRepository.findAll(new AddressesSpecification(criteria), pageable);
	}

	@Override
	public Addresses get(Long addressId) {
		return addressesRepository.findByAddressId(addressId);
	}

	@Override
	public Boolean delete(Long addressId) {
		if (addressesRepository.findByAddressId(addressId) != null) {
			addressesRepository.deleteById(addressId);
			return true;
		}
		return false;
	}

	@Override
	public Addresses create(Addresses addresses) {
		return addressesRepository.save(addresses);
	}

	@Override
	public Boolean save(Addresses addresses) {
		final Long pk = addresses.getAddressId();
		if (addressesRepository.findByAddressId(pk) != null) {
			addressesRepository.save(addresses);
			return true;
		}
		return false;
	}

	@Override
	public Boolean exist(Addresses addresses) {
		return addressesRepository.existsById(addresses.getAddressId());
	}

	class AddressesSpecification implements Specification<Addresses> {

		private AddressesCriteria criteria;

		public AddressesSpecification(AddressesCriteria criteria) {
			this.criteria = criteria;
		}

		@Override
		public Predicate toPredicate(Root<Addresses> root, CriteriaQuery<?> query, CriteriaBuilder builder) {
			final List<Predicate> predicates = new ArrayList<>();
			if (StringUtils.isNotBlank(criteria.getLine1NumberBuilding())) {
				predicates.add(builder.like(builder.lower(root.get("line1NumberBuilding")),
						criteria.getLine1NumberBuilding().toLowerCase() + "%"));
			}
			if (StringUtils.isNotBlank(criteria.getLine2NumberStreest())) {
				predicates.add(builder.like(builder.lower(root.get("line2NumberStreest")),
						criteria.getLine2NumberStreest().toLowerCase() + "%"));
			}
			if (StringUtils.isNotBlank(criteria.getLine3AreaLocality())) {
				predicates.add(builder.like(builder.lower(root.get("line3AreaLocality")),
						criteria.getLine3AreaLocality().toLowerCase() + "%"));
			}
			if (StringUtils.isNotBlank(criteria.getCity())) {
				predicates.add(builder.like(builder.lower(root.get("city")),
						criteria.getCity().toLowerCase() + "%"));
			}
			if (StringUtils.isNotBlank(criteria.getZipPostcode())) {
				predicates.add(builder.like(builder.lower(root.get("zipPostcode")),
						criteria.getZipPostcode().toLowerCase() + "%"));
			}
			if (StringUtils.isNotBlank(criteria.getStateProviceCounty())) {
				predicates.add(builder.like(builder.lower(root.get("stateProviceCounty")),
						criteria.getStateProviceCounty().toLowerCase() + "%"));
			}
			if (StringUtils.isNotBlank(criteria.getCountry())) {
				predicates.add(builder.like(builder.lower(root.get("country")),
						criteria.getCountry().toLowerCase() + "%"));
			}
			if (StringUtils.isNotBlank(criteria.getOrtherAddressDetails())) {
				predicates.add(builder.like(builder.lower(root.get("ortherAddressDetails")),
						criteria.getOrtherAddressDetails().toLowerCase() + "%"));
			}
			return andTogether(predicates, builder);
		}

		private Predicate andTogether(List<Predicate> predicates, CriteriaBuilder builder) {
			return builder.and(predicates.toArray(new Predicate[0]));
		}
	}

}
