/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.example.demo.entity.Addresses;
import com.example.demo.service.criteria.AddressesCriteria;

/**
 * Service interface for Addresses.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public interface AddressesService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @param criteria filters
	 * @return a page of addresses
	 */
	public Page<Addresses> search(Pageable pageable, AddressesCriteria criteria);
	/**
	 * Recover an addresses following an id.
	 * @param id the given id
	 * @return the addresses
	 */
	public Addresses get(Long addressId);

	/**
	 * Perform an addresses deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(Long addressId);

	/**
	 * Perform an addresses creation.
	 * @param addresses to create
	 * @return created addresses
	 */
	public Addresses create(Addresses addresses);

	/**
	 * Perform an addresses update.
	 * @param addresses to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(Addresses addresses);

	/**
	 * Test addresses existence.
	 * @param addresses to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(Addresses addresses);
}
