/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.example.demo.entity.AnazoneBook;
import com.example.demo.service.criteria.AnazoneBookCriteria;

/**
 * Service interface for AnazoneBook.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public interface AnazoneBookService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @param criteria filters
	 * @return a page of anazoneBook
	 */
	public Page<AnazoneBook> search(Pageable pageable, AnazoneBookCriteria criteria);
	/**
	 * Recover an anazoneBook following an id.
	 * @param id the given id
	 * @return the anazoneBook
	 */
	public AnazoneBook get(Long isbn);

	/**
	 * Perform an anazoneBook deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(Long isbn);

	/**
	 * Perform an anazoneBook creation.
	 * @param anazoneBook to create
	 * @return created anazoneBook
	 */
	public AnazoneBook create(AnazoneBook anazoneBook);

	/**
	 * Perform an anazoneBook update.
	 * @param anazoneBook to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(AnazoneBook anazoneBook);

	/**
	 * Test anazoneBook existence.
	 * @param anazoneBook to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(AnazoneBook anazoneBook);
}
