/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;

import com.example.demo.entity.Authors;
import com.example.demo.repository.AuthorsRepository;
import com.example.demo.service.criteria.AuthorsCriteria;

/**
 * Service implementation for Authors.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Service
public class AuthorsServiceImpl implements AuthorsService {

	@Autowired
	private AuthorsRepository authorsRepository;

	@Override
	public Page<Authors> search(Pageable pageable, AuthorsCriteria criteria) {
		return authorsRepository.findAll(new AuthorsSpecification(criteria), pageable);
	}

	@Override
	public Authors get(Long authorId) {
		return authorsRepository.findByAuthorId(authorId);
	}

	@Override
	public Boolean delete(Long authorId) {
		if (authorsRepository.findByAuthorId(authorId) != null) {
			authorsRepository.deleteById(authorId);
			return true;
		}
		return false;
	}

	@Override
	public Authors create(Authors authors) {
		return authorsRepository.save(authors);
	}

	@Override
	public Boolean save(Authors authors) {
		final Long pk = authors.getAuthorId();
		if (authorsRepository.findByAuthorId(pk) != null) {
			authorsRepository.save(authors);
			return true;
		}
		return false;
	}

	@Override
	public Boolean exist(Authors authors) {
		return authorsRepository.existsById(authors.getAuthorId());
	}

	class AuthorsSpecification implements Specification<Authors> {

		private AuthorsCriteria criteria;

		public AuthorsSpecification(AuthorsCriteria criteria) {
			this.criteria = criteria;
		}

		@Override
		public Predicate toPredicate(Root<Authors> root, CriteriaQuery<?> query, CriteriaBuilder builder) {
			final List<Predicate> predicates = new ArrayList<>();
			if (StringUtils.isNotBlank(criteria.getAuthorFirstName())) {
				predicates.add(builder.like(builder.lower(root.get("authorFirstName")),
						criteria.getAuthorFirstName().toLowerCase() + "%"));
			}
			if (StringUtils.isNotBlank(criteria.getAuthorLastName())) {
				predicates.add(builder.like(builder.lower(root.get("authorLastName")),
						criteria.getAuthorLastName().toLowerCase() + "%"));
			}
			return andTogether(predicates, builder);
		}

		private Predicate andTogether(List<Predicate> predicates, CriteriaBuilder builder) {
			return builder.and(predicates.toArray(new Predicate[0]));
		}
	}

}
