/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.example.demo.entity.BooksByCategories;

/**
 * Service interface for BooksByCategories.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public interface BooksByCategoriesService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @return a page of booksByCategories
	 */
	public Page<BooksByCategories> search(Pageable pageable);
	/**
	 * Recover an booksByCategories following an id.
	 * @param id the given id
	 * @return the booksByCategories
	 */
	public BooksByCategories get(Long isbn, Long caregoryId);

	/**
	 * Perform an booksByCategories deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(Long isbn, Long caregoryId);

	/**
	 * Perform an booksByCategories creation.
	 * @param booksByCategories to create
	 * @return created booksByCategories
	 */
	public BooksByCategories create(BooksByCategories booksByCategories);

	/**
	 * Perform an booksByCategories update.
	 * @param booksByCategories to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(BooksByCategories booksByCategories);

	/**
	 * Test booksByCategories existence.
	 * @param booksByCategories to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(BooksByCategories booksByCategories);
}
