/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.example.demo.entity.BookAtLibraries;
import com.example.demo.service.criteria.BookAtLibrariesCriteria;

/**
 * Service interface for BookAtLibraries.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public interface BookAtLibrariesService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @param criteria filters
	 * @return a page of bookAtLibraries
	 */
	public Page<BookAtLibraries> search(Pageable pageable, BookAtLibrariesCriteria criteria);
	/**
	 * Recover an bookAtLibraries following an id.
	 * @param id the given id
	 * @return the bookAtLibraries
	 */
	public BookAtLibraries get(Long libraryId, Long isbn);

	/**
	 * Perform an bookAtLibraries deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(Long libraryId, Long isbn);

	/**
	 * Perform an bookAtLibraries creation.
	 * @param bookAtLibraries to create
	 * @return created bookAtLibraries
	 */
	public BookAtLibraries create(BookAtLibraries bookAtLibraries);

	/**
	 * Perform an bookAtLibraries update.
	 * @param bookAtLibraries to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(BookAtLibraries bookAtLibraries);

	/**
	 * Test bookAtLibraries existence.
	 * @param bookAtLibraries to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(BookAtLibraries bookAtLibraries);
}
