/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.example.demo.entity.Libraries;
import com.example.demo.service.criteria.LibrariesCriteria;

/**
 * Service interface for Libraries.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public interface LibrariesService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @param criteria filters
	 * @return a page of libraries
	 */
	public Page<Libraries> search(Pageable pageable, LibrariesCriteria criteria);
	/**
	 * Recover an libraries following an id.
	 * @param id the given id
	 * @return the libraries
	 */
	public Libraries get(Long libraryId);

	/**
	 * Perform an libraries deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(Long libraryId);

	/**
	 * Perform an libraries creation.
	 * @param libraries to create
	 * @return created libraries
	 */
	public Libraries create(Libraries libraries);

	/**
	 * Perform an libraries update.
	 * @param libraries to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(Libraries libraries);

	/**
	 * Test libraries existence.
	 * @param libraries to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(Libraries libraries);
}
