/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:13:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.example.demo.service;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.example.demo.entity.MembersRequest;
import com.example.demo.service.criteria.MembersRequestCriteria;

/**
 * Service interface for MembersRequest.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public interface MembersRequestService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @param criteria filters
	 * @return a page of membersRequest
	 */
	public Page<MembersRequest> search(Pageable pageable, MembersRequestCriteria criteria);
	/**
	 * Recover an membersRequest following an id.
	 * @param id the given id
	 * @return the membersRequest
	 */
	public MembersRequest get(Long requestId);

	/**
	 * Perform an membersRequest deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(Long requestId);

	/**
	 * Perform an membersRequest creation.
	 * @param membersRequest to create
	 * @return created membersRequest
	 */
	public MembersRequest create(MembersRequest membersRequest);

	/**
	 * Perform an membersRequest update.
	 * @param membersRequest to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(MembersRequest membersRequest);

	/**
	 * Test membersRequest existence.
	 * @param membersRequest to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(MembersRequest membersRequest);
}
